version: "3"

services:
    bookmarker:
        image: djad/bookmarker
        ports:
            - "8090:8090"
        container_name: bookmarker
        entrypoint: ["java","-Dspring.profiles.active=test","-jar","bookmarker-0.0.1-SNAPSHOT.jar"]
        command: "--spring.datasource.url=jdbc:postgresql://172.17.0.1:5432/bookmarker"
