version: "3"

networks:
    net:

services:
    db:
        image: postgres
        networks:
            - net
        container_name: postgres
        environment: 
            POSTGRES_PASSWORD: postgres

    bookmarker:
        image: djad/bookmarker
        ports:
            - "8090:8090"
        networks:
            - net            
        container_name: bookmarker
        entrypoint: ["docker-entrypoint.sh"]
        depends_on:
            - db
        environment: 
            PGPASSWORD: postgres